travis:
  secure:
    BINSTAR_TOKEN: MXALUsCM+dPrcmuPR9n7zzbuv4SZdunwUfc5q2WgrafXNSrX9aTHzLx9gce3BJpnvQ1RHeU9n+qEDg/XQLyioS5DgL9o3YkBd9Z7Pn0qSRsvOF+NZe4I8RNGN40UCaKxb1fZ9TAc4MDb1wGzzdEViHU3PXAjR0mZ5DXFXwsNp5WPMpmEZVVCNiJGdBGWhd4xnIDFeHB+XpJABOVGeXxBLrkYlrtzr8541Pw32yICXw67BCj+z/KpV7Z4EKtdqqEpoRGGPY6LYZD/G5JzbIvmdw/mg6YkFU0yguM2LyotxZwLeLY8sEWeS7KRlF+AemYzgdJ1XrBZhE+nNyzzbIj+5QIbwq8KmzkfVA30o/+dIDSN6gnGRiuNmpbhyB845I0LTVbij3D0p1zuFM9g6p41+9cihm1r54Ko2bL0ZpnZd0dl8JuuxMytUH14In5WvLmPE8Mbg/jBt95lDCny4cr603kt+EDZu/A2ZrfrTTOvSieTKoiSZQCt380fATbYCVmcqqJPN2v3Yx7AiFknGM4IUfXPKqfx8gPv9zN5giSHiBOZGfvWgSfsptz+7KwkyuPzSZ4tgXM+FArQpxhSZ4UuBXqqYOViAhD+sDFtj40nTV95n0HoYKxue/28+wkJTUxsQzAWp2Uo4tJVfMHsbiWvgj3CdYT6ync+hm/U4W+YCak=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
