travis:
  secure:
    BINSTAR_TOKEN: yygayXcfIhuQ2f/FGiMHiJgZPrh2DavxZNjIdXPjGjtnWAxakOvonSklDzbKc4pwprFv6fBK+uayDDA0ayJmdTprcNtZehDoIrkkyV23095TsMV31E/dtni8CHt61T8YTx8o1knFYEp9XM3Hh0SkVIAjqFY84SmZI0YdVBh8Zz8DA2xKhRLMMX0Dy1fDWt+Yz7v59U9580btN2pFIH9z8QD0Ss1TlDgR0D5yM2Zf2HYrX2TckJUXUsM286s60agrSf2n7LlZbQQbFLurTOtVb9oY6p4At8ygSDf2kyAfYobzsT6m0kvF41qSt4MXnCOyAzQguZHqtRqdW9GLmG3Kp4dMtScY/f210f7R8CiXorq8tzGz5T3Bzx3x6GeIFqE40q/o8j2jiP7Svlsu3XYM+q53xzdgW1hz9h6wq/UfEE0pJhLKHWpETA6ALyLddQbD/0iC2+0IUnOTJrIDXEpaxnLp/hcTrjFPgX/e/817/XacgM6kmU5AZsGslKdFQjgyZSbZpooYFtMYvqJwMpBsH/UScoR390o9JBIUjksWl/TPGgzS43cfv7EFZkF998K99Tgi/JFnfPfAdzsZdKoLT29Lrao2J1UzDIJEqy+T0nw3jg1d1iuOCBGZtynxdLPhA7RZeIu+Afdoql0tTXaLuNRY9tcw4oKuljkNCYoPwz4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
